/* ctxmenu.js — the "everything has a right-click" layer.
   App-specific handlers run first (they preventDefault); this catches the rest. */
"use strict";
W98.Ctx = (() => {
  const isTextTarget = (t) =>
    t && (t.tagName === "TEXTAREA" ||
      (t.tagName === "INPUT" && /^(text|number|password|search|email|url)$/.test(t.type || "text")) ||
      t.isContentEditable);

  function insertText(t, text) {
    t.focus();
    if (t.isContentEditable) { document.execCommand("insertText", false, text); return; }
    const s = t.selectionStart ?? t.value.length, e2 = t.selectionEnd ?? t.value.length;
    t.value = t.value.slice(0, s) + text + t.value.slice(e2);
    t.selectionStart = t.selectionEnd = s + text.length;
    t.dispatchEvent(new Event("input", { bubbles: true }));
  }
  function selectedText(t) {
    if (t.isContentEditable) return String(window.getSelection());
    return (t.value || "").slice(t.selectionStart ?? 0, t.selectionEnd ?? 0);
  }
  function deleteSel(t) {
    if (t.isContentEditable) { document.execCommand("delete"); return; }
    const s = t.selectionStart, e2 = t.selectionEnd;
    if (s === e2) return;
    t.value = t.value.slice(0, s) + t.value.slice(e2);
    t.selectionStart = t.selectionEnd = s;
    t.dispatchEvent(new Event("input", { bubbles: true }));
  }

  function editMenu(t, x, y) {
    const sel = selectedText(t);
    const ro = t.readOnly || (t.tagName !== "TEXTAREA" && t.tagName !== "INPUT" && !t.isContentEditable);
    Menu.popup(x, y, [
      { label: "Undo", disabled: ro, click: () => { t.focus(); document.execCommand("undo"); } },
      "-",
      { label: "Cut", disabled: !sel || ro, click: () => {
        W98.clipText = sel;
        navigator.clipboard && navigator.clipboard.writeText(sel).catch(() => {});
        deleteSel(t);
      }},
      { label: "Copy", disabled: !sel, click: () => {
        W98.clipText = sel;
        navigator.clipboard && navigator.clipboard.writeText(sel).catch(() => {});
      }},
      { label: "Paste", disabled: ro, click: async () => {
        let text = null;
        try { text = await navigator.clipboard.readText(); } catch (e2) {}
        if (text == null) text = W98.clipText || "";
        if (text) insertText(t, text);
      }},
      { label: "Delete", disabled: !sel || ro, click: () => deleteSel(t) },
      "-",
      { label: "Select All", click: () => {
        t.focus();
        if (t.isContentEditable) document.execCommand("selectAll");
        else t.select();
      }}
    ]);
  }

  function iePageMenu(pageEl, winEl, x, y) {
    const tool = (label) => [...winEl.querySelectorAll(".tbtn")].find(b => (b.textContent || "").trim().startsWith(label));
    const backB = tool("Back"), fwdB = tool("Forward"), refB = tool("Refresh");
    Menu.popup(x, y, [
      { label: "Back", disabled: !backB || backB.disabled, click: () => backB.click() },
      { label: "Forward", disabled: !fwdB || fwdB.disabled, click: () => fwdB.click() },
      { label: "Refresh", disabled: !refB, click: () => refB && refB.click() },
      "-",
      { label: "Select All", click: () => {
        const r = document.createRange();
        r.selectNodeContents(pageEl);
        const s = window.getSelection();
        s.removeAllRanges(); s.addRange(r);
      }},
      { label: "View Source", click: () => {
        const src = "<!-- generated by the 1998 internet -->\n" + pageEl.innerHTML
          .replace(/></g, ">\n<").slice(0, 20000);
        const w2 = W98.launch("notepad");
        setTimeout(() => {
          const ta = w2 && w2.body ? w2.body.querySelector("textarea") : null;
          if (ta) { ta.value = src; w2.setTitle && w2.setTitle("source.htm - Notepad"); }
        }, 150);
      }},
      "-",
      { label: "Properties", click: () => WM.msgbox({ title: "Page Properties", icon: "info", text: "Protocol: HyperText Transfer Protocol\nType: HTML Document\nConnection: 28.8k (allegedly)\nEncrypted: absolutely not" }) }
    ]);
  }

  function dosMenu(screenEl, x, y) {
    Menu.popup(x, y, [
      { label: "Copy Screen Text", click: () => {
        const t = screenEl.textContent || "";
        W98.clipText = t;
        navigator.clipboard && navigator.clipboard.writeText(t).catch(() => {});
      }},
      { label: "Paste", click: async () => {
        let text = null;
        try { text = await navigator.clipboard.readText(); } catch (e2) {}
        if (text == null) text = W98.clipText || "";
        if (!text) return;
        const ta = screenEl.parentElement.querySelector("textarea");
        if (ta) {
          ta.focus();
          ta.value = text.replace(/\n/g, "");
          ta.dispatchEvent(new Event("input", { bubbles: true }));
        }
      }},
      "-",
      { label: "Mark (select text)", click: () => {
        const r = document.createRange();
        r.selectNodeContents(screenEl);
        const s = window.getSelection();
        s.removeAllRanges(); s.addRange(r);
      }}
    ]);
  }

  document.addEventListener("contextmenu", (e) => {
    if (e.defaultPrevented) return;             /* an app already handled it */
    const t = e.target;

    /* 1. text fields anywhere: the classic edit menu */
    if (isTextTarget(t)) {
      e.preventDefault();
      editMenu(t, e.clientX, e.clientY);
      return;
    }
    /* 2. IE page */
    const page = t.closest && t.closest(".ie-page");
    if (page) {
      e.preventDefault();
      iePageMenu(page, t.closest(".win") || document.body, e.clientX, e.clientY);
      return;
    }
    /* 3. DOS / terminal screens */
    const dos = t.closest && t.closest(".dos-screen");
    if (dos) {
      e.preventDefault();
      dosMenu(dos, e.clientX, e.clientY);
      return;
    }
    /* 4. per-window registered menus (games etc.) */
    const winEl = t.closest && t.closest(".win");
    if (winEl) {
      const win = W98.WM.wins.find(w => w.el === winEl);
      if (win && win.ctxMenu) {
        const items = win.ctxMenu(e);
        if (items && items.length) {
          e.preventDefault();
          Menu.popup(e.clientX, e.clientY, items);
        }
      }
    }
  });

  return { editMenu };
})();
